// قائمة الدول القابلة للعب في محاكاة أرجوس (أجواء سنة 1900)
const COUNTRIES = [
  { code: 'US', name: 'الولايات المتحدة', flag: '🇺🇸' },
  { code: 'GB', name: 'بريطانيا', flag: '🇬🇧' },
  { code: 'FR', name: 'فرنسا', flag: '🇫🇷' },
  { code: 'DE', name: 'ألمانيا', flag: '🇩🇪' },
  { code: 'RU', name: 'روسيا', flag: '🇷🇺' },
  { code: 'AT', name: 'النمسا-المجر', flag: '🇦🇹' },
  { code: 'IT', name: 'إيطاليا', flag: '🇮🇹' },
  { code: 'OT', name: 'الدولة العثمانية', flag: '🇹🇷' },
  { code: 'JP', name: 'اليابان', flag: '🇯🇵' },
  { code: 'ES', name: 'إسبانيا', flag: '🇪🇸' },
  { code: 'BE', name: 'بلجيكا', flag: '🇧🇪' },
  { code: 'NL', name: 'هولندا', flag: '🇳🇱' },
  { code: 'PT', name: 'البرتغال', flag: '🇵🇹' },
  { code: 'GR', name: 'اليونان', flag: '🇬🇷' },
  { code: 'RS', name: 'صربيا', flag: '🇷🇸' },
  { code: 'CN', name: 'الصين', flag: '🇨🇳' },
  { code: 'IR', name: 'بلاد فارس', flag: '🇮🇷' },
  { code: 'ET', name: 'إثيوبيا', flag: '🇪🇹' },
  { code: 'BR', name: 'البرازيل', flag: '🇧🇷' },
  { code: 'AR', name: 'الأرجنتين', flag: '🇦🇷' },
  { code: 'MX', name: 'المكسيك', flag: '🇲🇽' },
  { code: 'MA', name: 'المغرب', flag: '🇲🇦' },
  { code: 'DZ', name: 'الجزائر', flag: '🇩🇿' },
  { code: 'TN', name: 'تونس', flag: '🇹🇳' },
  { code: 'LY', name: 'ليبيا', flag: '🇱🇾' },
  { code: 'EG', name: 'مصر', flag: '🇪🇬' },
  { code: 'SD', name: 'السودان', flag: '🇸🇩' },
  { code: 'MR', name: 'موريتانيا', flag: '🇲🇷' },
  { code: 'SA', name: 'السعودية', flag: '🇸🇦' },
  { code: 'YE', name: 'اليمن', flag: '🇾🇪' },
  { code: 'IQ', name: 'العراق', flag: '🇮🇶' },
  { code: 'JO', name: 'الأردن', flag: '🇯🇴' },
  { code: 'SY', name: 'سوريا', flag: '🇸🇾' },
  { code: 'LB', name: 'لبنان', flag: '🇱🇧' },
  { code: 'PS', name: 'فلسطين', flag: '🇵🇸' },
  { code: 'KW', name: 'الكويت', flag: '🇰🇼' },
  { code: 'QA', name: 'قطر', flag: '🇶🇦' },
  { code: 'BH', name: 'البحرين', flag: '🇧🇭' },
  { code: 'OM', name: 'عُمان', flag: '🇴🇲' },
  { code: 'AE', name: 'الإمارات', flag: '🇦🇪' },
  { code: 'SO', name: 'الصومال', flag: '🇸🇴' },
  { code: 'DJ', name: 'جيبوتي', flag: '🇩🇯' },
  { code: 'KM', name: 'جزر القمر', flag: '🇰🇲' },
];

module.exports = { COUNTRIES };
