// الدول والكيانات المستقلة سنة 1900 — قائمة الحجز في لعبة أرجوس
const COUNTRIES = [
  // أوروبا
  { code: 'GB', name: 'بريطانيا', flag: '🇬🇧' },
  { code: 'FR', name: 'فرنسا', flag: '🇫🇷' },
  { code: 'DE', name: 'ألمانيا', flag: '🇩🇪' },
  { code: 'AT', name: 'النمسا-المجر', flag: '🇦🇹' },
  { code: 'RU', name: 'الإمبراطورية الروسية', flag: '🇷🇺' },
  { code: 'OT', name: 'الدولة العثمانية', flag: '🇹🇷' },
  { code: 'IT', name: 'إيطاليا', flag: '🇮🇹' },
  { code: 'ES', name: 'إسبانيا', flag: '🇪🇸' },
  { code: 'PT', name: 'البرتغال', flag: '🇵🇹' },
  { code: 'NL', name: 'هولندا', flag: '🇳🇱' },
  { code: 'BE', name: 'بلجيكا', flag: '🇧🇪' },
  { code: 'CH', name: 'سويسرا', flag: '🇨🇭' },
  { code: 'SN', name: 'السويد والنرويج', flag: '🇸🇪' },
  { code: 'DK', name: 'الدنمارك', flag: '🇩🇰' },
  { code: 'GR', name: 'اليونان', flag: '🇬🇷' },
  { code: 'RS', name: 'صربيا', flag: '🇷🇸' },
  { code: 'RO', name: 'رومانيا', flag: '🇷🇴' },
  { code: 'BG', name: 'بلغاريا', flag: '🇧🇬' },
  { code: 'ME', name: 'الجبل الأسود', flag: '🇲🇪' },
  { code: 'LU', name: 'لوكسمبورغ', flag: '🇱🇺' },
  // آسيا
  { code: 'JP', name: 'اليابان', flag: '🇯🇵' },
  { code: 'CN', name: 'الصين (تشينغ)', flag: '🇨🇳' },
  { code: 'IR', name: 'بلاد فارس', flag: '🇮🇷' },
  { code: 'TH', name: 'سيام', flag: '🇹🇭' },
  { code: 'AF', name: 'أفغانستان', flag: '🇦🇫' },
  { code: 'KR', name: 'كوريا', flag: '🇰🇷' },
  { code: 'NP', name: 'نيبال', flag: '🇳🇵' },
  // أفريقيا
  { code: 'ET', name: 'إثيوبيا', flag: '🇪🇹' },
  { code: 'LR', name: 'ليبيريا', flag: '🇱🇷' },
  { code: 'MA', name: 'المغرب', flag: '🇲🇦' },
  { code: 'TV', name: 'ترانسفال', flag: '🇿🇦' },
  { code: 'OF', name: 'أورانج الحرة', flag: '🇿🇦' },
  // الأمريكتان
  { code: 'US', name: 'الولايات المتحدة', flag: '🇺🇸' },
  { code: 'MX', name: 'المكسيك', flag: '🇲🇽' },
  { code: 'GT', name: 'غواتيمالا', flag: '🇬🇹' },
  { code: 'HN', name: 'هندوراس', flag: '🇭🇳' },
  { code: 'SV', name: 'السلفادور', flag: '🇸🇻' },
  { code: 'NI', name: 'نيكاراغوا', flag: '🇳🇮' },
  { code: 'CR', name: 'كوستاريكا', flag: '🇨🇷' },
  { code: 'CO', name: 'كولومبيا', flag: '🇨🇴' },
  { code: 'VE', name: 'فنزويلا', flag: '🇻🇪' },
  { code: 'EC', name: 'الإكوادور', flag: '🇪🇨' },
  { code: 'PE', name: 'بيرو', flag: '🇵🇪' },
  { code: 'BO', name: 'بوليفيا', flag: '🇧🇴' },
  { code: 'CL', name: 'تشيلي', flag: '🇨🇱' },
  { code: 'AR', name: 'الأرجنتين', flag: '🇦🇷' },
  { code: 'UY', name: 'الأوروغواي', flag: '🇺🇾' },
  { code: 'PY', name: 'الباراغواي', flag: '🇵🇾' },
  { code: 'BR', name: 'البرازيل', flag: '🇧🇷' },
  { code: 'HT', name: 'هايتي', flag: '🇭🇹' },
  { code: 'DO', name: 'الدومينيكان', flag: '🇩🇴' },
  // الجزيرة العربية
  { code: 'OM', name: 'عُمان', flag: '🇴🇲' },
  { code: 'HS', name: 'إمارة حائل', flag: '🏴' },
];
module.exports = { COUNTRIES };
